# compose.yaml


services:
  influxdb2:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${TOKEN_INFLUXDB}
      DOCKER_INFLUXDB_INIT_ORG: ${ORGANISATION}
      DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET}
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    networks:
      - app

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    ports:
      - "5555:5555"
    entrypoint: ["sh", "/entrypoint-telegraf.sh"]
    volumes:
      - ./telegraf/entrypoint-telegraf.sh:/entrypoint-telegraf.sh:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
    environment:
      BUCKET: ${BUCKET}
      ORGANISATION: ${ORGANISATION}
      TOKEN_INFLUXDB: ${TOKEN_INFLUXDB}
    networks:
      - app
    depends_on:
      - influxdb2

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - app
    depends_on:
      - influxdb2

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  app:
